media: src/images
content:
  - name: homepage
    label: Home Page
    type: file
    path: src/pages/index.md
  - name: pages
    label: Pages
    type: collection
    path: src/pages
    exclude: [ index.md ]
    fields:
      - name: title
        type: string
      - name: layout
        type: string
        default: "../layouts/PageLayout.astro"
        hidden: true
      - name: imgPath
        type: string
      - name: body
        type: rich-text
        options:
          format: html
