import { create, insertMultiple, save as saveOramaDB } from "@orama/orama";

async function getInMemoryTestDatabase() {
    const schema = {
        id: "string",
        type: "enum",
        repository: "enum",
        repository_city: "enum",
        repository_nation: "enum",
        repository_name_and_city: "string",
        lib_latitude: "string",
        lib_longitude: "string",
        shelfmark: "string",
        date_start: "string",
        date_end: "string",
        date_quality: "enum",
        provenance: "string",
        provenance_quality: "string",
        provenance_latitude: "string",
        provenance_longitude: "string",
        length: "string",
        width: "string",
        number_of_pieces: "string",
        orientation: "string",
        completed: "string",
        language_1: "enum",
        language_2: "enum",
        contents: "string",
        description: "string",
        bibliography: "string",
        editor_initials: "string",
        online_images: "string",
        online_bibliography_record: "string",
        wp_type: "string",
        wp_id: "string",
        meta_title: "string",
        slug: "string",
      }
    
    const testData = [
      {
          "id": "1",
          "type": "Prayer Roll",
          "repository": "Bibliothèque Royale",
          "repository_city": "Brussels",
          "repository_nation": "BE",
          "repository_name_and_city": "Bibliothèque Royale, Brussels BE",
          "lib_latitude": "",
          "lib_longitude": "",
          "shelfmark": "MS IV 247",
          "date_start": "1475",
          "date_end": "1500",
          "date_quality": "",
          "provenance": "Italy",
          "provenance_latitude": "",
          "provenance_longitude": "",
          "length": "79",
          "width": "16.5",
          "number_of_pieces": "",
          "orientation": "",
          "completed": "",
          "language_1": "Latin",
          "language_2": "Italian",
          "contents": "Prayers in Latin.",
          "description": "142 Lines.",
          "bibliography": "Stork, Hans-Walter. “Spätmittelalterliche Gebetsbücher in Rollenform in Überlieferung Und Bild” Gutenberg Jahrbuch 20 (2010): 43–78.",
          "editor_initials": "",
          "online_images": "",
          "online_bibliography_record": "",
          "wp_type": "scroll",
          "wp_id": "4562",
          "meta_title": "Brussels, BE, Bibliothèque Royale, MS IV.247",
          "slug": "brussels-be-bibliotheque-royale-ms-iv-247"
      },
      {
          "id": "3",
          "type": "Poetry",
          "repository": "Houghton Library",
          "repository_city": "Cambridge, MA",
          "repository_nation": "US",
          "repository_name_and_city": "Houghton Library, Cambridge MA US",
          "lib_latitude": "",
          "lib_longitude": "",
          "shelfmark": "MS Typ 550",
          "date_start": "1400",
          "date_end": "1500",
          "date_quality": "",
          "provenance": "Italy",
          "provenance_latitude": "",
          "provenance_longitude": "",
          "length": "80.6",
          "width": "13.7",
          "number_of_pieces": "15",
          "orientation": "V",
          "completed": "",
          "language_1": "Latin",
          "language_2": "",
          "contents": "Devotional poems of St. Bernard.",
          "description": "",
          "bibliography": "The Houghton Library Report of Accessions, 1966-1968. Cambridge, MA: Harvard College Library, 1969.",
          "editor_initials": " ",
          "online_images": "http://pds.lib.harvard.edu/pds/view/4074278",
          "online_bibliography_record": "http://hcl.harvard.edu/libraries/houghton/collections/early_manuscripts/bibliographies/Typ/Typ550.html",
          "wp_type": "scroll",
          "wp_id": "4802",
          "meta_title": "Cambridge, MA, US, Houghton Library, MS Typ 550",
          "slug": "cambridge-ma-us-houghton-library-ms-typ-550"
      },
      {
          "id": "4",
          "type": "Amulets",
          "repository": "Canterbury Cathedral",
          "repository_city": "Canterbury",
          "repository_nation": "GB",
          "repository_name_and_city": "Canterbury Cathedral, Canterbury GB",
          "lib_latitude": "",
          "lib_longitude": "",
          "shelfmark": "Additional MS 23",
          "date_start": "1200",
          "date_end": "1300",
          "date_quality": "ca",
          "provenance": "England",
          "provenance_latitude": "",
          "provenance_longitude": "",
          "length": "51.2",
          "width": "42.7",
          "number_of_pieces": "2",
          "orientation": "",
          "completed": "",
          "language_1": "Unknown Language",
          "language_2": "",
          "contents": "\"Earliest extant multipurpose textual amulet based on an amalgamation of old and new magic.\" (Skemer, p. 199)",
          "description": "",
          "bibliography": "Skemer, Don C. Binding Words: Textual Amulets in the Middle Ages. Magic in History. University Park, PA: Pennsylvania State University Press, 2006, 199-215, plates on pp. 200-201.",
          "editor_initials": "KWS",
          "online_images": "",
          "online_bibliography_record": "",
          "wp_type": "scroll",
          "wp_id": "4725",
          "meta_title": "Canterbury, GB, Canterbury Cathedral, Additional MS 23",
          "slug": "canterbury-gb-canterbury-cathedral-additional-ms-23"
      },
      {
          "id": "5",
          "type": "Amulets",
          "repository": "British Library",
          "repository_city": "London",
          "repository_nation": "GB",
          "repository_name_and_city": "British Library, London GB",
          "lib_latitude": "",
          "lib_longitude": "",
          "shelfmark": "add MS 15505 fol. 22r",
          "date_start": "1500",
          "date_end": "1600",
          "date_quality": "ca",
          "provenance": "Italy",
          "provenance_latitude": "",
          "provenance_longitude": "",
          "length": "45",
          "width": "31",
          "number_of_pieces": "1",
          "orientation": "",
          "completed": "",
          "language_1": "Latin",
          "language_2": "Italian",
          "contents": "Textual amulet belonging to an unidentified Italian man named \"Francesco\".",
          "description": "",
          "bibliography": "Skemer, Don C. Binding Words: Textual Amulets in the Middle Ages. Magic in History. University Park, PA: Pennsylvania State University Press, 2006, 214-217, plate on p. 214.",
          "editor_initials": "KWS",
          "online_images": "",
          "online_bibliography_record": "http://searcharchives.bl.uk/primo_library/libweb/action/display.do?tabs=detailsTab&ct=display&fn=search&doc=IAMS032-002087277&indx=1&recIds=IAMS032-002087277&recIdxs=0&elementId=0&renderMode=poppedOut&displayMode=full&frbrVersion=&dscnt=1&frbg=&scp.scps=scope%3A%28BL%29&tab=local&dstmp=1404148162521&srt=rank&mode=Basic&dum=true&vl(freeText0)=add+ms+15505&vid=IAMS_VU2",
          "wp_type": "scroll",
          "wp_id": "4705",
          "meta_title": "London, GB, British Library, add MS 15505 fol. 22r",
          "slug": "london-gb-british-library-add-ms-15505-fol-22r"
      },
      {
          "id": "6",
          "type": "Amulets",
          "repository": "British Library",
          "repository_city": "London",
          "repository_nation": "GB",
          "repository_name_and_city": "British Library, London GB",
          "lib_latitude": "",
          "lib_longitude": "",
          "shelfmark": "add MS 25311",
          "date_start": "1600",
          "date_end": "1700",
          "date_quality": "",
          "provenance": "Unknown Provenance",
          "provenance_latitude": "",
          "provenance_longitude": "",
          "length": "332.74",
          "width": "3.81",
          "number_of_pieces": "",
          "orientation": "V",
          "completed": "",
          "language_1": "Latin",
          "language_2": "",
          "contents": "Magical images with prayers. Contains on one side magical signs for charms against diseases, wounds, etc. and on the other prayers in Latin.",
          "description": "Opisthographic. Written on vellum.",
          "bibliography": "Simpson, W. Sparrow. “On a Magical Roll of the Seventeenth Century.” Journal of the British Archaeological Association XL (1884): 297–332, 297.",
          "editor_initials": "SDP",
          "online_images": "",
          "online_bibliography_record": "http://searcharchives.bl.uk/primo_library/libweb/action/display.do?tabs=detailsTab&ct=display&fn=search&doc=IAMS032-002032603&indx=1&recIds=IAMS032-002032603&recIdxs=0&elementId=0&renderMode=poppedOut&displayMode=full&frbrVersion=&dscnt=1&frbg=&scp.scps=scope%3A%28BL%29&tab=local&dstmp=1403977120224&srt=rank&mode=Basic&dum=true&vl(freeText0)=add+MS+25311&vid=IAMS_VU2",
          "wp_type": "scroll",
          "wp_id": "4704",
          "meta_title": "London, GB, British Library, add MS 25311",
          "slug": "london-gb-british-library-add-ms-25311"
      },
      {
          "id": "7",
          "type": "Amulets",
          "repository": "British Library",
          "repository_city": "London",
          "repository_nation": "GB",
          "repository_name_and_city": "British Library, London GB",
          "lib_latitude": "",
          "lib_longitude": "",
          "shelfmark": "add MS 88929",
          "date_start": "1485",
          "date_end": "1509",
          "date_quality": "",
          "provenance": "England",
          "provenance_latitude": "",
          "provenance_longitude": "",
          "length": "335.5",
          "width": "12",
          "number_of_pieces": "4",
          "orientation": "V",
          "completed": "",
          "language_1": "English",
          "language_2": "Latin",
          "contents": "Illustrated prayers, ratio of images 1:15. Scroll to be worn or placed on women in childbirth. Emblem of Henry VIII.",
          "description": "",
          "bibliography": "McKendrick, Scott, John Lowden, Kathleen Doyle, Joanna Frońska, and Deirdre Elizabeth Jackson. Royal Manuscripts: The Genius of Illumination. London: British Library, 2011., no. 44, pp. 186-87.",
          "editor_initials": "NDP (added info)",
          "online_images": "http://www.bl.uk/manuscripts/FullDisplay.aspx?ref=Add_MS_88929",
          "online_bibliography_record": "http://searcharchives.bl.uk/primo_library/libweb/action/display.do?tabs=detailsTab&ct=display&fn=search&doc=IAMS032-001606303&indx=2&recIds=IAMS032-001606303&recIdxs=1&elementId=1&renderMode=poppedOut&displayMode=full&frbrVersion=&dscnt=1&frbg=&scp.scps=scope%3A%28BL%29&tab=local&dstmp=1404147197769&srt=rank&mode=Basic&dum=true&vl(freeText0)=arma+christi&vid=IAMS_VU2",
          "wp_type": "scroll",
          "wp_id": "4692",
          "meta_title": "London, GB, British Library, add MS 88929",
          "slug": "london-gb-british-library-add-ms-88929"
      },
      {
          "id": "8",
          "type": "Amulets",
          "repository": "British Library",
          "repository_city": "London",
          "repository_nation": "GB",
          "repository_name_and_city": "British Library, London GB",
          "lib_latitude": "",
          "lib_longitude": "",
          "shelfmark": "Harley Ch 43.A.14",
          "date_start": "1400",
          "date_end": "1500",
          "date_quality": "?",
          "provenance": "Unknown Provenance",
          "provenance_latitude": "",
          "provenance_longitude": "",
          "length": "Unknown",
          "width": "Unknown",
          "number_of_pieces": "",
          "orientation": "",
          "completed": "",
          "language_1": "Latin",
          "language_2": "English",
          "contents": "A small roll apparently used as a charm amulet. At the beginning is a representation of a Cross drawn with a pen. \"This cross XV [tymys] [...tyn] ys the length of our Lord Jesus Christe, and that day that thou beryst it upon the or lookist thereupon thou shalt have thise grete giftes.\"",
          "description": "Written on vellum.",
          "bibliography": "Bühler, Curt F. “Prayers and Charms in Certain Middle English Scrolls.” Speculum 39, no. 2 (1964): 270–78. 274",
          "editor_initials": "",
          "online_images": "http://www.bl.uk/manuscripts/FullDisplay.aspx?ref=Harley_Ch_43_A_14",
          "online_bibliography_record": "",
          "wp_type": "scroll",
          "wp_id": "4657",
          "meta_title": "London, GB, British Library, Harley Rot 43.A.14",
          "slug": "london-gb-british-library-harley-rot-43-a-14"
      },
      {
          "id": "9",
          "type": "Amulets",
          "repository": "Private collection",
          "repository_city": "London",
          "repository_nation": "GB",
          "repository_name_and_city": "Private collection, London GB",
          "lib_latitude": "",
          "lib_longitude": "",
          "shelfmark": "Private Collection",
          "date_start": "1300",
          "date_end": "1500",
          "date_quality": "",
          "provenance": "France",
          "provenance_latitude": "",
          "provenance_longitude": "",
          "length": "105",
          "width": "39",
          "number_of_pieces": "1",
          "orientation": "",
          "completed": "",
          "language_1": "Unknown Language",
          "language_2": "",
          "contents": "Amulet against disease and demons.",
          "description": "",
          "bibliography": "Skemer, Don C. “Amulet Rolls and Female Devotion in the Late Middle Ages.” Scriptorium 55 (2001): 197–227.; Skemer, Don C. Binding Words: Textual Amulets in the Middle Ages. Magic in History. University Park, PA: Pennsylvania State University Press, 2006, 251-259, 305-307.",
          "editor_initials": "KWS (bibliography)",
          "online_images": "",
          "online_bibliography_record": "",
          "wp_type": "scroll",
          "wp_id": "4926",
          "meta_title": "London, GB, Private collection, Private Collection",
          "slug": "london-gb-private-collection-private-collection"
      },
      {
          "id": "10",
          "type": "Amulets",
          "repository": "Wellcome Historical Medical Library",
          "repository_city": "London",
          "repository_nation": "GB",
          "repository_name_and_city": "Wellcome Historical Medical Library, London GB",
          "lib_latitude": "",
          "lib_longitude": "",
          "shelfmark": "MS 632",
          "date_start": "1500",
          "date_end": "1500",
          "date_quality": "ca",
          "provenance": "Unknown Provenance",
          "provenance_latitude": "",
          "provenance_longitude": "",
          "length": "332",
          "width": "10",
          "number_of_pieces": "4",
          "orientation": "",
          "completed": "",
          "language_1": "Latin",
          "language_2": "English",
          "contents": "Prayers and invocations to Saint Quiricus and Saint Julitta, his mother; with other prayers and invoctions against all evils spiritual and temporal, and for safe delivery in childbirth.",
          "description": "6 emblematic figures associated with Christ's passion: 3 nails, instruments of Passion, 2 images of letters IHS, a crucifix, a figure of Christ standing.",
          "bibliography": "Bühler, Curt F. “Prayers and Charms in Certain Middle English Scrolls.” Speculum 39, no. 2 (1964): 270–78. 272n23.; Moorat, S.A.J. Catalogue of Western Manuscripts on Medicine and Science in the Wellcome Historical Medical Library. I. MSS. Written before 1650 A. D. London: The Wellcome Historical Medical Library, 1962. 491-3; Stork, Hans-Walter. “Spätmittelalterliche Gebetsbücher in Rollenform in Überlieferung Und Bild.” Gutenberg Jahrbuch 20 (2010): 43–78.",
          "editor_initials": "",
          "online_images": "",
          "online_bibliography_record": "http://archives.wellcomelibrary.org/DServe/dserve.exe?dsqIni=Dserve.ini&dsqApp=Archive&dsqCmd=Show.tcl&dsqDb=Catalog&dsqPos=0&dsqSearch=%28AltRefNo%3D%27MS.632%27%29",
          "wp_type": "scroll",
          "wp_id": "5030",
          "meta_title": "London, GB, Wellcome Historical Medical Library, MS 632",
          "slug": "london-gb-wellcome-historical-medical-library-ms-632"
      },
      {
          "id": "11",
          "type": "Amulets",
          "repository": "Wellcome Historical Medical Library",
          "repository_city": "London",
          "repository_nation": "GB",
          "repository_name_and_city": "Wellcome Historical Medical Library, London GB",
          "lib_latitude": "",
          "lib_longitude": "",
          "shelfmark": "MS 804",
          "date_start": "1465",
          "date_end": "1465",
          "date_quality": "ca.",
          "provenance": "France",
          "provenance_latitude": "",
          "provenance_longitude": "",
          "length": "250",
          "width": "11",
          "number_of_pieces": "",
          "orientation": "V",
          "completed": "N",
          "language_1": "Latin",
          "language_2": "",
          "contents": "Life of Saint Margaret in verse [Beginning wanting].",
          "description": "Written in a neat gothic script, on one side only. There are 25 small illuminated ornamental initials in gold and colours. This manuscript. is written in scroll form so as to be used as a 'Birthgirdle' (cf. MS. No. 632 in Vol. I of this Catalogue].",
          "bibliography": "Ker, N.R. Medieval Manuscripts in British Libraries. Vol. I. Oxford: Clarendon, 1969, p. 400-401",
          "editor_initials": "SDP (edited shelfmark/link)",
          "online_images": "",
          "online_bibliography_record": "http://archives.wellcomelibrary.org/DServe/dserve.exe?dsqIni=Dserve.ini&dsqApp=Archive&dsqCmd=Show.tcl&dsqDb=Catalog&dsqPos=0&dsqSearch=%28AltRefNo%3D%27MS.804%27%29",
          "wp_type": "scroll",
          "wp_id": "5031",
          "meta_title": "London, GB, Wellcome Historical Medical Library, MS 804",
          "slug": "london-gb-wellcome-historical-medical-library-ms-804"
      },
      {
          "id": "12",
          "type": "Amulets",
          "repository": "Wellcome Historical Medical Library",
          "repository_city": "London",
          "repository_nation": "GB",
          "repository_name_and_city": "Wellcome Historical Medical Library, London GB",
          "lib_latitude": "",
          "lib_longitude": "",
          "shelfmark": "MS 804A",
          "date_start": "1485",
          "date_end": "1485",
          "date_quality": "ca.",
          "provenance": "Unknown Provenance",
          "provenance_latitude": "",
          "provenance_longitude": "",
          "length": "125",
          "width": "9",
          "number_of_pieces": "4",
          "orientation": "V",
          "completed": "N",
          "language_1": "Latin",
          "language_2": "",
          "contents": "Life of St. Margret in Latin.",
          "description": "Two strips sewn together; written in verse.",
          "bibliography": "Ker, N.R. Medieval Manuscripts in British Libraries. Vol. I. Oxford: Clarendon, 1969, p. 401.",
          "editor_initials": "SDP (edited shelfmark/link)",
          "online_images": "",
          "online_bibliography_record": "http://archives.wellcomelibrary.org/DServe/dserve.exe?dsqIni=Dserve.ini&dsqApp=Archive&dsqCmd=Show.tcl&dsqDb=Catalog&dsqPos=0&dsqSearch=%28AltRefNo%3D%27MS.804A%27%29",
          "wp_type": "scroll",
          "wp_id": "5032",
          "meta_title": "London, GB, Wellcome Historical Medical Library, MS 804A",
          "slug": "london-gb-wellcome-historical-medical-library-ms-804a"
      },
      {
          "id": "13",
          "type": "Amulets",
          "repository": "Bayerische Staatsbibliothek",
          "repository_city": "Munich",
          "repository_nation": "DE",
          "repository_name_and_city": "Bayerische Staatsbibliothek, Munich DE",
          "lib_latitude": "",
          "lib_longitude": "",
          "shelfmark": "CIm 10098",
          "date_start": "1300",
          "date_end": "1350",
          "date_quality": "ca",
          "provenance": "Italian",
          "provenance_latitude": "",
          "provenance_longitude": "",
          "length": "594.4",
          "width": "11",
          "number_of_pieces": "3",
          "orientation": "",
          "completed": "",
          "language_1": "Latin",
          "language_2": "",
          "contents": "Penitential psalms, litany, prayers to saints.",
          "description": "",
          "bibliography": "Stork, Hans-Walter. “Spätmittelalterliche Gebetsbücher in Rollenform in Überlieferung Und Bild.” Gutenberg Jahrbuch 20 (2010): 43–78.",
          "editor_initials": "SDP",
          "online_images": "",
          "online_bibliography_record": "http://www.manuscripta-mediaevalia.de/hs/katalogseiten/HSK0240_b075_jpg.htm",
          "wp_type": "scroll",
          "wp_id": "4419",
          "meta_title": "Munich, DE, Bayerische Staatsbibliothek, CIm 10098",
          "slug": "munich-de-bayerische-staatsbibliothek-cim-10098"
      },
      {
          "id": "14",
          "type": "Amulets",
          "repository": "Pierpont Morgan Library",
          "repository_city": "New York, NY",
          "repository_nation": "US",
          "repository_name_and_city": "Pierpont Morgan Library, New York NY US",
          "lib_latitude": "",
          "lib_longitude": "",
          "shelfmark": "M 1092",
          "date_start": "1491",
          "date_end": "1491",
          "date_quality": "",
          "provenance": "France, Paris",
          "provenance_latitude": "",
          "provenance_longitude": "",
          "length": "397",
          "width": "9.8",
          "number_of_pieces": "6",
          "orientation": "",
          "completed": "",
          "language_1": "French",
          "language_2": "",
          "contents": "French life of St. Margaret",
          "description": "One rubbed illustration.",
          "bibliography": "Stork, Hans-Walter. “Spätmittelalterliche Gebetsbücher in Rollenform in Überlieferung Und Bild.” Gutenberg Jahrbuch 20 (2010): 43–78.",
          "editor_initials": "",
          "online_images": "http://corsair.themorgan.org/cgi-bin/Pwebrecon.cgi?BBID=343690",
          "online_bibliography_record": "http://corsair.themorgan.org/cgi-bin/Pwebrecon.cgi?BBID=160675",
          "wp_type": "scroll",
          "wp_id": "4914",
          "meta_title": "New York, NY, US, Pierpont Morgan Library, M 1092",
          "slug": "new-york-ny-us-pierpont-morgan-library-m-1092"
      },
      {
          "id": "15",
          "type": "Amulets",
          "repository": "Pierpont Morgan Library",
          "repository_city": "New York, NY",
          "repository_nation": "US",
          "repository_name_and_city": "Pierpont Morgan Library, New York NY US",
          "lib_latitude": "",
          "lib_longitude": "",
          "shelfmark": "MS M 779",
          "date_start": "1445",
          "date_end": "1455",
          "date_quality": "ca",
          "provenance": "Belgium",
          "provenance_latitude": "",
          "provenance_longitude": "",
          "length": "392.5",
          "width": "10.1",
          "number_of_pieces": "6",
          "orientation": "",
          "completed": "",
          "language_1": "French",
          "language_2": "Latin",
          "contents": "Legend of St. Margaret of Antioch in Verse.",
          "description": "",
          "bibliography": "Skemer, Don C. “Amulet Rolls and Female Devotion in the Late Middle Ages.” Scriptorium 55 (2001): 197–227.",
          "editor_initials": "ECI",
          "online_images": "http://corsair.themorgan.org/cgi-bin/Pwebrecon.cgi?BBID=338111",
          "online_bibliography_record": "http://corsair.themorgan.org/cgi-bin/Pwebrecon.cgi?BBID=143964",
          "wp_type": "scroll",
          "wp_id": "4913",
          "meta_title": "New York, NY, US, Pierpont Morgan Library, MS M 779",
          "slug": "new-york-ny-us-pierpont-morgan-library-ms-m-779"
      },
      {
          "id": "16",
          "type": "Amulets",
          "repository": "Private collection",
          "repository_city": "New York, NY",
          "repository_nation": "US",
          "repository_name_and_city": "Private collection, New York NY\tUS",
          "lib_latitude": "",
          "lib_longitude": "",
          "shelfmark": "Private Collection",
          "date_start": "1480",
          "date_end": "1500",
          "date_quality": "ca",
          "provenance": "Germany",
          "provenance_latitude": "",
          "provenance_longitude": "",
          "length": "85",
          "width": "18.5",
          "number_of_pieces": "",
          "orientation": "",
          "completed": "",
          "language_1": "Latin",
          "language_2": "",
          "contents": "Lanthrop Harper catalog 13 1961 #4.",
          "description": "",
          "bibliography": "Stork, Hans-Walter. “Spätmittelalterliche Gebetsbücher in Rollenform in Überlieferung Und Bild.” Gutenberg Jahrbuch 20 (2010): 43–78.",
          "editor_initials": "",
          "online_images": "",
          "online_bibliography_record": "",
          "wp_type": "scroll",
          "wp_id": "4927",
          "meta_title": "New York, NY, US, Private collection, Private Collection",
          "slug": "new-york-ny-us-private-collection-private-collection"
      },
      {
          "id": "17",
          "type": "Amulets",
          "repository": "Bodleian Library",
          "repository_city": "Oxford",
          "repository_nation": "GB",
          "repository_name_and_city": "Bodleian Library, Oxford GB",
          "lib_latitude": "",
          "lib_longitude": "",
          "shelfmark": "MS Lat. liturg. e. 11",
          "date_start": "1400",
          "date_end": "1500",
          "date_quality": "",
          "provenance": "England",
          "provenance_latitude": "",
          "provenance_longitude": "",
          "length": "79",
          "width": "14",
          "number_of_pieces": "2",
          "orientation": "",
          "completed": "",
          "language_1": "Latin",
          "language_2": "",
          "contents": "Memory of St Christopher, office connected with the passion, rhymed prayers.",
          "description": "",
          "bibliography": "Hunt, Richard William. A Summary Catalogue of Western Manuscripts in the Bodleian Library at Oxford Which Have Not Hitherto Been Catalogued in the Quarto Series: With References to the Oriental and Other Manuscripts. Oxford: Clarendon Press, 1895, no. 30560; Robbins, Rossell Hope. “The‘ Arma Christi’ Rolls.” The Modern Language Review 34, no. 3 (1939): 415–21.",
          "editor_initials": "SDP (edited)",
          "online_images": "",
          "online_bibliography_record": "",
          "wp_type": "scroll",
          "wp_id": "4598",
          "meta_title": "Oxford, GB, Bodleian Library, MS Lat. liturg. e. 11",
          "slug": "oxford-gb-bodleian-library-ms-lat-liturg-e-11"
      },
      {
          "id": "18",
          "type": "Amulets",
          "repository": "Princeton University Library",
          "repository_city": "Princeton, NJ",
          "repository_nation": "US",
          "repository_name_and_city": "Princeton University Library, Princeton NJ US",
          "lib_latitude": "",
          "lib_longitude": "",
          "shelfmark": "Scheide MS 7923",
          "date_start": "1500",
          "date_end": "1600",
          "date_quality": "ca",
          "provenance": "Italy",
          "provenance_latitude": "",
          "provenance_longitude": "",
          "length": "29.5",
          "width": "18.3",
          "number_of_pieces": "1",
          "orientation": "",
          "completed": "",
          "language_1": "Unknown Language",
          "language_2": "",
          "contents": "Textual amulet belonging to an unidentified Italian man named Ilioneo.",
          "description": "",
          "bibliography": "Skemer, Don C. Binding Words: Textual Amulets in the Middle Ages. Magic in History. University Park, PA: Pennsylvania State University Press, 2006, 217-222, plate on p. 218.",
          "editor_initials": "KWS",
          "online_images": "",
          "online_bibliography_record": "",
          "wp_type": "scroll",
          "wp_id": "4921",
          "meta_title": "Princeton, NJ, US, Princeton University Library, Scheide MS 7923",
          "slug": "princeton-nj-us-princeton-university-library-scheide-ms-7923"
      },
      {
          "id": "19",
          "type": "Amulets",
          "repository": "Universitätsbibliothek Rostock",
          "repository_city": "Rostock",
          "repository_nation": "DE",
          "repository_name_and_city": "Universitätsbibliothek Rostock, Rostock DE",
          "lib_latitude": "",
          "lib_longitude": "",
          "shelfmark": "MS Theol. 45a",
          "date_start": "1400",
          "date_end": "1450",
          "date_quality": "",
          "provenance": "Germany, Lower",
          "provenance_latitude": "",
          "provenance_longitude": "",
          "length": "70",
          "width": "14.7",
          "number_of_pieces": "",
          "orientation": "",
          "completed": "",
          "language_1": "German",
          "language_2": "",
          "contents": "Prayer cycle for daily use.",
          "description": "121 lines. Florinated initials.",
          "bibliography": "Stork, Hans-Walter. “Spätmittelalterliche Gebetsbücher in Rollenform in Überlieferung Und Bild.” Gutenberg Jahrbuch 20 (2010): 43–78.",
          "editor_initials": "SDP (edited/link)",
          "online_images": "",
          "online_bibliography_record": "http://www.manuscripta-mediaevalia.de/hs/katalogseiten/HSK0544_b240_jpg.htm",
          "wp_type": "scroll",
          "wp_id": "5011",
          "meta_title": "Rostock, DE, Universitätsbibliothek Rostock, MS Theol. 45a",
          "slug": "rostock-de-universitatsbibliothek-rostock-ms-theol-45a"
      },
      {
          "id": "20",
          "type": "Amulets",
          "repository": "Bibliothèque Municipale",
          "repository_city": "Sens",
          "repository_nation": "FR",
          "repository_name_and_city": "Bibliothèque Municipale, Sens FR",
          "lib_latitude": "",
          "lib_longitude": "",
          "shelfmark": "MS 39",
          "date_start": "1465",
          "date_end": "1465",
          "date_quality": "ca",
          "provenance": "France, Avignon",
          "provenance_latitude": "",
          "provenance_longitude": "",
          "length": "682.5",
          "width": "11.5",
          "number_of_pieces": "",
          "orientation": "",
          "completed": "",
          "language_1": "French",
          "language_2": "Latin",
          "contents": "Prayers, illuminated",
          "description": "",
          "bibliography": "Stork, Hans-Walter. “Spätmittelalterliche Gebetsbücher in Rollenform in Überlieferung Und Bild.” Gutenberg Jahrbuch 20 (2010): 43–78.",
          "editor_initials": "",
          "online_images": "",
          "online_bibliography_record": "https://archive.org/stream/cataloguegnr061887fran#page/156/mode/2up/search/Sens",
          "wp_type": "scroll",
          "wp_id": "4506",
          "meta_title": "Sens, FR, Bibliothèque Municipale, MS 39",
          "slug": "sens-fr-bibliotheque-municipale-ms-39"
      },
      {
          "id": "21",
          "type": "Amulets",
          "repository": "Private collection",
          "repository_city": "Unknown",
          "repository_nation": "IT",
          "repository_name_and_city": "Private collection, Unknown IT",
          "lib_latitude": "",
          "lib_longitude": "",
          "shelfmark": "Private Collection",
          "date_start": "1400",
          "date_end": "1500",
          "date_quality": "",
          "provenance": "Unknown Provenance",
          "provenance_latitude": "",
          "provenance_longitude": "",
          "length": "Unknown",
          "width": "Unknown",
          "number_of_pieces": "",
          "orientation": "",
          "completed": "",
          "language_1": "Unknown Language",
          "language_2": "",
          "contents": "Penitential psalms.",
          "description": "Illuminated.",
          "bibliography": "Dalli, Regoli G. “Una Tipologia Insolita: Un Rotolo Miniato Contenente I Salmi Pentenziali.” In La Miniatura Italiana Tra Gotico E Rinascimento: Atti Del II Congresso Di Storia Della Miniatura Italiana, Cortona 24-26 Settembre 1982, edited by Emanuela Sesti, 6:297–308. Storia Della Miniatura, 1985.",
          "editor_initials": "",
          "online_images": "",
          "online_bibliography_record": "",
          "wp_type": "scroll",
          "wp_id": "4931",
          "meta_title": "Unknown, IT, Private collection, Private Collection",
          "slug": "unknown-it-private-collection-private-collection"
      },
      {
          "id": "22",
          "type": "Med-Alch",
          "repository": "Private collection",
          "repository_city": "Unknown",
          "repository_nation": "Unknown",
          "repository_name_and_city": "Private collection, Unknown Unknown",
          "lib_latitude": "",
          "lib_longitude": "",
          "shelfmark": "Lot 34",
          "date_start": "1500",
          "date_end": "1600",
          "date_quality": "?",
          "provenance": "Germany",
          "provenance_latitude": "",
          "provenance_longitude": "",
          "length": "271",
          "width": "9.5",
          "number_of_pieces": "5",
          "orientation": "",
          "completed": "",
          "language_1": "German",
          "language_2": "Latin",
          "contents": "Colored roundels containing alchemical talismans, with explanantions in Latin and German. Prayers on dorse.",
          "description": "Opisthographic.",
          "bibliography": "Unknown Bibliography",
          "editor_initials": "ECI",
          "online_images": "http://www.sothebys.com/en/auctions/ecatalogue/2010/western-manuscripts-and-miniatures-l10241/lot.34.html",
          "online_bibliography_record": "http://www.sothebys.com/en/auctions/ecatalogue/2010/western-manuscripts-and-miniatures-l10241/lot.34.html",
          "wp_type": "scroll",
          "wp_id": "4933",
          "meta_title": "Unknown, Unknown, Private collection, Lot 34",
          "slug": "unknown-unknown-private-collection-lot-34"
      },
      {
          "id": "23",
          "type": "Amulets",
          "repository": "Unknown",
          "repository_city": "Unknown",
          "repository_nation": "Unknown",
          "repository_name_and_city": "Unknown Location",
          "lib_latitude": "",
          "lib_longitude": "",
          "shelfmark": "Unknown",
          "date_start": "1430",
          "date_end": "1430",
          "date_quality": "ca",
          "provenance": "Unknown Provenance",
          "provenance_latitude": "",
          "provenance_longitude": "",
          "length": "584.6",
          "width": "17.8",
          "number_of_pieces": "",
          "orientation": "V",
          "completed": "",
          "language_1": "Unknown Language",
          "language_2": "",
          "contents": "Headed by a miniature of the Virgin and Child. Contains: Septem Psalmi Penitentiales cum Litania (Sarum).",
          "description": "",
          "bibliography": "Stork, Hans-Walter. “Spätmittelalterliche Gebetsbücher in Rollenform in Überlieferung Und Bild.” Gutenberg Jahrbuch 20 (2010): 43–78.",
          "editor_initials": "",
          "online_images": "",
          "online_bibliography_record": "",
          "wp_type": "scroll",
          "wp_id": "5026",
          "meta_title": "Unknown, Unknown, Unknown, Unknown 1",
          "slug": "unknown-unknown-unknown-unknown-1"
      },
      {
          "id": "25",
          "type": "Amulets",
          "repository": "Historisches Museum Frankfurt am Main",
          "repository_city": "Frankfurt am Main",
          "repository_nation": "DE",
          "repository_name_and_city": "Historisches Museum Frankfurt am Main, Frankfurt am Main De",
          "lib_latitude": "",
          "lib_longitude": "",
          "shelfmark": "Germ oct 27",
          "date_start": "1450",
          "date_end": "1450",
          "date_quality": "ca",
          "provenance": "Netherlands",
          "provenance_latitude": "",
          "provenance_longitude": "",
          "length": "66.9",
          "width": "10.2",
          "number_of_pieces": "",
          "orientation": "",
          "completed": "",
          "language_1": "Dutch",
          "language_2": "",
          "contents": "Prayers in Dutch.",
          "description": "",
          "bibliography": "Stork, Hans-Walter. “Spätmittelalterliche Gebetsbücher in Rollenform in Überlieferung Und Bild” Gutenberg Jahrbuch 20 (2010): 43–78.",
          "editor_initials": "",
          "online_images": "http://sammlungen.ub.uni-frankfurt.de/msma/id/3663073",
          "online_bibliography_record": "http://sammlungen.ub.uni-frankfurt.de/kataloge/purn/urn:nbn:de:hebis:30:2-282-p0136-8",
          "wp_type": "scroll",
          "wp_id": "5025",
          "meta_title": "Unknown, Unknown, urt, StuLB, Germ oct 27",
          "slug": "unknown-unknown-urt-stulb-germ-oct-27"
      },
      {
          "id": "27",
          "type": "Archival",
          "repository": "Durham Cathedral",
          "repository_city": "Durham",
          "repository_nation": "GB",
          "repository_name_and_city": "Durham Cathedral, Durham GB",
          "lib_latitude": "",
          "lib_longitude": "",
          "shelfmark": "Loc I:19",
          "date_start": "1350",
          "date_end": "1350",
          "date_quality": "ca",
          "provenance": "Unknown Provenance",
          "provenance_latitude": "",
          "provenance_longitude": "",
          "length": "79",
          "width": "21",
          "number_of_pieces": "",
          "orientation": "",
          "completed": "",
          "language_1": "Latin",
          "language_2": "",
          "contents": "Articles for an inquisition into the king's [Edward III?] subjects, their rights and their misdemeanours, and especially those of royal officers including sheriffs, bailiffs, coroners, and escheators.",
          "description": "",
          "bibliography": "Unknown Bibliography",
          "editor_initials": "SDP",
          "online_images": "",
          "online_bibliography_record": "http://reed.dur.ac.uk/xtf/view?docId=ead/dcd/dcdlocel.xml#qxj-40",
          "wp_type": "scroll",
          "wp_id": "4772",
          "meta_title": "Durham, GB, Durham Cathedral, Loc I:19",
          "slug": "durham-gb-durham-cathedral-loc-i19"
      }
    ];
    const db = create({
      schema,
      components: {
        tokenizer: {
          stemming: true,
          stemmerSkipProperties: [
            "repository",
            "repository_city",
            "repository_nation",
            "type",
            "language_1",
            "language_2",
          ],
        },
      },
    });
    await insertMultiple(db, testData);
    return db;
}

export { getInMemoryTestDatabase };
