name: Build and Deploy Astro
on:
  push:
    branches:
      - main
  workflow_dispatch:
  repository_dispatch:
    types: [build-trigger]

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js current
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc

      - name: Install dependencies & build
        run: |
          npm install --legacy-peer-deps
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          # publish_branch is the branch in the repository.
          # this is where you need to point GitHub pages
          publish_branch: gh-pages
